apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-spring-deploy
  namespace: coffee-ns
  labels:
    app: coffee-spring-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-spring-deploy
  template:
    metadata:
      labels:
        app: coffee-spring-deploy
    spec:
      containers:
      - name: coffee-spring
        image: parksewoong/fullmoon-spring:coffee
        ports:
          - containerPort: 8080
