apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-deploy
  name: front-deploy
  namespace: front-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-deploy
    spec:
      containers:
      - image: ohhong/fullmoon_frontend:test2
        name: front
        resources: {}
status: {}
